sudo: false
language: ruby
rvm:
- 2.2.2
before_install:
- sudo apt-get update
- sudo apt-get install -y build-essential
install:
- bundle install --path vendor --binstubs
script:
- bin/berks install
- bundle exec rspec --color
