sudo: false
language: ruby
cache:
  bundler: true
  directories:
  - .berkshelf 
rvm:
- 2.2.2
addons:
  apt:
    packages:
    - build-essential
install:
- bundle install --path vendor --binstubs
script:
- bin/berks install
- bundle exec rspec --color
